print("=====================")
print("Welcome to Calculator")
print("=====================")

print("+ for addition, - for subtraction, * for multiplication, / for division")
sign=input()
if sign=="+":
    print("First number to add")
    num1=input()
    print("Okay, I will add", num1)
    print("Second Number?")
    num2=input()
    sum = int(num1) + int(num2)
    print(num1, "+", num2, "=", sum)
if sign=="-":
    print("First number to subtract")
    num1=input()
    print("Okay, I will subtract", num1)
    print("Second Number?")
    num2=input()
    sum = int(num1) - int(num2)
    print(num1, "-", num2, "=", sum)
if sign=="*":
    print("First number to multiply")
    num1=input()
    print("Okay, I will multiply", num1)
    print("Second Number?")
    num2=input()
    sum = int(num1) * int(num2)
    print(num1, "x", num2, "=", sum)
if sign=="/":
    print("First number to divide")
    num1=input()
    print("Okay, I will divide", num1)
    print("Second Number?")
    num2=input()
    sum = int(num1) / int(num2)
    print(num1, "÷", num2, "=", sum)
